import type { Program } from "@/types/Program"

// Mock program data for guest mode when database is not available
export const mockPrograms: Program[] = [
  {
    id: "1",
    name: "Master in International Business",
    university: "ESSEC Business School",
    country: "France",
    city: "Paris",
    study_level: "Master",
    field: "Business",
    program_language: "English",
    secondary_language: "French",
    duration_months: 24,
    tuition_min: 15000,
    tuition_max: 20000,
    living_cost_min: 800,
    living_cost_max: 1200,
    application_fee: 100,
    status: "Active",
    description:
      "A comprehensive international business program designed to prepare students for global leadership roles. The program combines theoretical knowledge with practical experience through internships and international exchanges.",
    advantages: "International exposure, Strong alumni network, Industry partnerships, Career support",
    admission_requirements:
      "Bachelor's degree with minimum 3.0 GPA, GMAT/GRE scores, English proficiency test, Statement of purpose, Letters of recommendation",
    academic_requirements: "Bachelor's degree in any field with minimum 3.0 GPA",
    language_requirement: "IELTS 6.5 or TOEFL 90",
    language_test: "IELTS, TOEFL, Cambridge English",
    language_test_score: "IELTS 6.5, TOEFL 90",
    language_test_exemptions: "Native English speakers or previous education in English",
    application_deadline: "2025-03-15",
    scholarship_available: true,
    scholarship_amount: 5000,
    scholarship_deadline: "2025-02-15",
    scholarship_details: "Merit-based scholarships available for outstanding students",
    scholarship_requirements: "Minimum 3.5 GPA and demonstrated leadership experience",
    gpa_requirement: "3.0",
    application_process: "Online application through university portal with required documents",
    internship_opportunities: true,
    exchange_opportunities: true,
    employment_rate: 92,
    success_rate: 85,
    ranking: 15,
    total_places: 120,
    available_places: 45,
    north_african_community_size: "Medium",
    religious_facilities: true,
    halal_food_availability: true,
    housing_availability: "On-campus and off-campus housing available",
    housing_cost_min: 400,
    housing_cost_max: 800,
    visa_fee: 99,
    field_keywords: ["International Business", "Management", "Strategy", "Marketing", "Finance"],
    image_url: "/placeholder.svg?height=400&width=600&text=ESSEC+Business+School",
    video_url: "https://example.com/video",
    virtual_tour_url: "https://example.com/tour",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "MBA in Global Management",
    university: "HEC Paris",
    country: "France",
    city: "Paris",
    study_level: "Master",
    field: "Business",
    program_language: "English",
    secondary_language: "French",
    duration_months: 16,
    tuition_min: 25000,
    tuition_max: 30000,
    living_cost_min: 900,
    living_cost_max: 1400,
    application_fee: 150,
    status: "Active",
    description:
      "A world-class MBA program that develops global business leaders through innovative curriculum and international exposure.",
    advantages: "Top-ranked program, Global network, Executive coaching, Consulting projects",
    admission_requirements: "Bachelor's degree, 3+ years work experience, GMAT 650+, English proficiency",
    academic_requirements: "Bachelor's degree with strong academic record",
    language_requirement: "IELTS 7.0 or TOEFL 100",
    language_test: "IELTS, TOEFL, Cambridge English",
    language_test_score: "IELTS 7.0, TOEFL 100",
    language_test_exemptions: "Native speakers or previous MBA in English",
    application_deadline: "2025-04-01",
    scholarship_available: true,
    scholarship_amount: 10000,
    scholarship_deadline: "2025-03-01",
    scholarship_details: "Need-based and merit-based scholarships available",
    scholarship_requirements: "Financial need demonstration and academic excellence",
    gpa_requirement: "3.2",
    application_process: "Online application with essays, recommendations, and interview",
    internship_opportunities: true,
    exchange_opportunities: true,
    employment_rate: 95,
    success_rate: 90,
    ranking: 8,
    total_places: 80,
    available_places: 25,
    north_african_community_size: "Large",
    religious_facilities: true,
    halal_food_availability: true,
    housing_availability: "Limited on-campus housing, assistance with off-campus",
    housing_cost_min: 500,
    housing_cost_max: 1000,
    visa_fee: 99,
    field_keywords: ["MBA", "Global Management", "Leadership", "Strategy", "Innovation"],
    image_url: "/placeholder.svg?height=400&width=600&text=HEC+Paris",
    video_url: "https://example.com/video",
    virtual_tour_url: "https://example.com/tour",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Master in Computer Science",
    university: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    study_level: "Master",
    field: "Computer Science",
    program_language: "English",
    secondary_language: "German",
    duration_months: 24,
    tuition_min: 0,
    tuition_max: 500,
    living_cost_min: 700,
    living_cost_max: 1100,
    application_fee: 75,
    status: "Active",
    description:
      "A cutting-edge computer science program focusing on artificial intelligence, machine learning, and software engineering.",
    advantages: "No tuition fees, Strong industry connections, Research opportunities, High employment rate",
    admission_requirements:
      "Bachelor's in Computer Science or related field, Strong programming skills, English proficiency",
    academic_requirements: "Bachelor's degree in Computer Science with minimum 2.5 German grade",
    language_requirement: "IELTS 6.5 or TOEFL 88",
    language_test: "IELTS, TOEFL, Cambridge English",
    language_test_score: "IELTS 6.5, TOEFL 88",
    language_test_exemptions: "Previous degree taught in English",
    application_deadline: "2025-02-28",
    scholarship_available: true,
    scholarship_amount: 3000,
    scholarship_deadline: "2025-01-31",
    scholarship_details: "DAAD scholarships and university grants available",
    scholarship_requirements: "Academic excellence and research potential",
    gpa_requirement: "2.5",
    application_process: "Online application through uni-assist with transcripts and certificates",
    internship_opportunities: true,
    exchange_opportunities: true,
    employment_rate: 98,
    success_rate: 88,
    ranking: 12,
    total_places: 150,
    available_places: 60,
    north_african_community_size: "Medium",
    religious_facilities: true,
    halal_food_availability: true,
    housing_availability: "Student dormitories and private housing available",
    housing_cost_min: 300,
    housing_cost_max: 600,
    visa_fee: 75,
    field_keywords: ["Computer Science", "AI", "Machine Learning", "Software Engineering", "Data Science"],
    image_url: "/placeholder.svg?height=400&width=600&text=TU+Munich",
    video_url: "https://example.com/video",
    virtual_tour_url: "https://example.com/tour",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
]

// Function to get mock program by ID
export const getMockProgramById = (id: string) => {
  console.warn("Mock data access attempted - this should not happen in production")
  return null
}

// Function to get mock programs with filters
export const getMockPrograms = (filters?: any): Program[] => {
  console.warn("Mock data access attempted - this should not happen in production")
  return []
}

