// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzdmouebmzugmadypibz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZG1vdWVibXp1Z21hZHlwaWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjYzMDMsImV4cCI6MjA1OTk0MjMwM30.wmEwqIoAwDSsfulWommJ60bijyszwYFRghkN7955hq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);