// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ochjuhaljyvjxiwvomnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaGp1aGFsanl2anhpd3ZvbW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTA1NDAsImV4cCI6MjA1Njg2NjU0MH0.z1Oka22Z8d2oP9qCYsumnJaFn4bIbQB1CCq031U0fFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);